version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: identifier of the order
          - name: products_id
            description: identifier of the product
          - name: revenue
            description: revenue by order
          - name: quantity
            description: quantity ordered
      - name: product
        identifier: raw_gz_product
        description: list of products of greenweez / list of purchase_price by products_id
        columns:
          - name: products_id
            description: identifier of the product
            tests:
              - unique
              - not_null                 
          - name: purchase_price
            description: purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: list of shipping fee per order
        columns:
          - name: orders_id
            description: identifier of the order
          - name: shipping_fee
            description: fee of shipping of the order
          - name: logcost
            description: cost of warehousing the order
          - name: ship_cost
            description: cost of the shipping per order
      - name: adwords
        identifier: raw_gz_adwords
        description: list of adwords campaign
        columns:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: Adwords
          - name: campaign_key
            description: id of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: nb of impression by campaign
          - name: click
            description: nb of click by campaign
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: list of bing campaign
        columns:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: Bing
          - name: campaign_key
            description: id of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: nb of impression by campaign
          - name: click
            description: nb of click by campaign
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: list of criteo campaign
        columns:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: Criteo
          - name: campaign_key
            description: id of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: nb of impression by campaign
          - name: click
            description: nb of click by campaign
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: list of facebook campaign
        columns:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: Facebook
          - name: campaign_key
            description: id of the campaign
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: nb of impression by campaign
          - name: click
            description: nb of click by campaign
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"